Add pulseaudio server for audio.
projectceladon/vm_manager pull request #166
Opened 2022-03-23 07:14 UTC by padmashree9110

This patch adds pulseaudio server path for
audiobackend driver pa.

Signed-off-by: pmandri <padmashree.mandri@intel.com>

2022-03-24 06:51 UTC, YadongQi requested changes

2022-03-24 06:51 UTC, YadongQi commented on src/guest/start.c
> +	" -audiodev id=android_spk,timer-period=5000,driver=pa,server=/run/user/1000/pulse/native,in.fixed-settings=off,out.fixed-settings=off"
Do not hardcode 1000 here, the user id might not 1000

2022-03-25 01:38 UTC, YadongQi requested changes

2022-03-25 01:38 UTC, YadongQi commented on src/guest/start.c
> +int get_uid() {
make it static if it is only used in this file.

2022-03-25 01:38 UTC, YadongQi commented on src/guest/start.c
> +	p += cx; size -= cx;
move this block code to above extra groups (line 1129) since it is not fixed cmd any more.

2022-03-25 08:25 UTC, YadongQi approved these changes

2022-03-28 05:47 UTC, gkdeepa approved these changes
looks good to me

2022-03-28 06:03 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/4122

2022-03-28 11:08 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/4123

Done by "Mandri, Padmashree" <padmashree.mandri@intel.com>

2022-03-28 13:06 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/2312

Done by "Mandri, Padmashree" <padmashree.mandri@intel.com>

2022-03-28 16:07 UTC, merged

2022-03-28 16:08 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Mandri, Padmashree" <padmashree.mandri@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/2785