start host camera service
projectceladon/vm_manager pull request #182
Opened 2022-06-03 16:59 UTC by shivasku82

2022-06-06 04:25 UTC, gkdeepa approved these changes
LGTM

2022-06-06 05:05 UTC, YadongQi requested changes

2022-06-06 05:05 UTC, YadongQi commented on src/guest/start.c
> +		run_camera_mediation_daemon("./scripts/stream");
do not assume stream is under where vm-manager is executed. use run_camera_mediation_daemon(val); That is why we need CAMERA_MED sub key

2022-06-06 05:05 UTC, YadongQi commented on scripts/setup_host.sh
> +    sudo rm -rf ../../../host_camera
maybe you can install stream to /usr/local/bin/ ?

2022-06-14 00:50 UTC, YadongQi approved these changes

2022-06-15 10:30 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/4268

2022-06-15 15:01 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/4269

Done by "Rudrappa, Shiva Kumara" <shiva.kumara.rudrappa@intel.com>

2022-06-15 16:32 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: Trigger blocking tests Triggered: CIT-CIV-TGL-R(tgl_nuc:caas - userdebug), CIT-CIV-TGL-R(tgl_nuc:r2_caas - userdebug)

More details, logs, and binaries: /absp/builders/celadon-premerge/builds/2423

2022-06-16 03:27 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: Trigger blocking tests Triggered: CIT-CIV-TGL-R(tgl_nuc:caas - userdebug), CIT-CIV-TGL-R(tgl_nuc:r2_caas - userdebug)

More details, logs, and binaries: /absp/builders/celadon-premerge/builds/2424

2022-06-20 02:29 UTC, YadongQi approved these changes

2022-06-20 07:18 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/4273

Done by "Rudrappa, Shiva Kumara" <shiva.kumara.rudrappa@intel.com>

2022-06-21 03:28 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: Trigger blocking tests Triggered: CIT-CIV-TGL-R(tgl_nuc:caas - userdebug), CIT-CIV-TGL-R(tgl_nuc:r2_caas - userdebug)

More details, logs, and binaries: /absp/builders/celadon-premerge/builds/2425

2022-06-24 08:50 UTC, YadongQi approved these changes

2022-06-24 20:15 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: Trigger blocking tests Triggered: CIT-CIV-TGL-R(tgl_nuc:caas - userdebug), CIT-CIV-TGL-R(tgl_nuc:r2_caas - userdebug)

More details, logs, and binaries: /absp/builders/celadon-premerge/builds/2436

2022-06-28 00:47 UTC, YadongQi approved these changes

2022-06-28 07:18 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/4293

Done by "Rudrappa, Shiva Kumara" <shiva.kumara.rudrappa@intel.com>

2022-06-28 14:27 UTC, merged

2022-06-28 14:27 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Rudrappa, Shiva Kumara" <shiva.kumara.rudrappa@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/2863