Port vertical changes
projectceladon/vm_manager pull request #282
Opened 2022-12-28 11:19 UTC by prashanth-intel

2023-01-16 03:45 UTC, YadongQi commented on scripts/setup_civ_ini.sh
> +function setup_civ_ini() {
I think its better to keep this script file in vertical.

2023-01-16 03:47 UTC, YadongQi commented
The S branch has been into maintaince status, features are not accepted in genneral unless there is a strong requirement. Please make sure you really want these new updates.
And please also fix the code scaning issues.

2023-01-19 11:11 UTC, prashanth-intel commented
> The S branch has been into maintaince status, features are not accepted in genneral unless there is a strong requirement. Please make sure you really want these new updates. And please also fix the code scaning issues.

Hi Yadong. Removed the commit for ini file. Fixed all relevant code scanning issues. There is one issue which does not seem critical as I am appending an integer and not string.

2023-01-20 01:43 UTC, YadongQi commented
> > The S branch has been into maintaince status, features are not accepted in genneral unless there is a strong requirement. Please make sure you really want these new updates. And please also fix the code scaning issues.
> 
> Hi Yadong. Removed the commit for ini file. Fixed all relevant code scanning issues. There is one issue which does not seem critical as I am appending an integer and not string.

Suggest to use strncat() to avoid unsafe use of strcat().

2023-01-20 01:43 UTC, YadongQi commented on scripts/setup_host.sh
> +setup_civ_ini
calling inexistent function?

2023-01-20 06:40 UTC, prashanth-intel commented
> > > The S branch has been into maintaince status, features are not accepted in genneral unless there is a strong requirement. Please make sure you really want these new updates. And please also fix the code scaning issues.
> > 
> > 
> > Hi Yadong. Removed the commit for ini file. Fixed all relevant code scanning issues. There is one issue which does not seem critical as I am appending an integer and not string.
> 
> Suggest to use strncat() to avoid unsafe use of strcat().

Done. Thanks for the suggestion.

2023-01-20 09:16 UTC, YadongQi requested changes

2023-01-20 09:16 UTC, YadongQi commented on src/guest/start.c
> +		}
sizeof(qmp_pwr_socket) always > 0, so the condition always true. I think you mean to:
```
if (strlen(num) < (sizeof(qmp_pwr_socket) - strlen(qmp_pwr_socket)) {
    strncat(qmp_pwr_socket, num, (sizeof(qmp_pwr_socket) - strlen(qmp_pwr_socket));
}
```

2023-01-20 09:16 UTC, YadongQi commented on src/guest/start.c
> +	const char qmp_sock[MAX_CMDLINE_LEN] = { 0 };
remove `const ` qualifier.

2023-01-20 09:16 UTC, YadongQi commented on src/guest/start.c
> +void set_pwr_ctrl(char * qmp_cmd) {
add `static` qualifier for this function.

2023-01-20 09:16 UTC, YadongQi commented on src/guest/start.c
> +void cleanup_pwr_ctrl() {
add `static` qualifier for this function.

2023-01-30 00:57 UTC, YadongQi approved these changes

2023-02-07 09:27 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/283

2023-02-07 09:45 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/284

2023-02-07 10:57 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Update Bugs And Epics Update Bugs And Epics

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/287

2023-02-07 11:58 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/290

2023-02-07 14:36 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Update Bugs And Epics Update Bugs And Epics

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/291

2023-02-07 14:39 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/292

2023-02-08 04:19 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/293

2023-02-08 06:16 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-cels - r1 (caas), build-cels - r1 (caas_sriov), build-cels - r2 (r2_caas), build-cels - r2 (r2_caas_sriov) - extra

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/294

2023-02-08 06:47 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds cancelled

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/296

2023-02-08 14:47 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds cancelled

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/299

2023-02-08 17:53 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/297

Done by "Suresh, Prashanth" <prashanth.suresh@intel.com>

2023-02-08 21:04 UTC, merged

2023-02-08 21:05 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Suresh, Prashanth" <prashanth.suresh@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_stable-mergerequest/builds/134