Bring down BT-HCI Inteface before Passthrough
projectceladon/vm_manager pull request #353
Opened 2024-04-10 13:39 UTC by gowthambabu92

0000:00:14.0 is the Intel BT-Card Pci address, so before the passthrough is done we are brining down the interface.

Tracked-On: OAM-116593

2024-04-10 13:42 UTC, sysopenci commented
Building VM-Manager Code. For more details refer below link: 
job/satg-aee-android-ci/job/VM-Manager/job/VM-MANAGER-PR-FLOW/201/

2024-04-10 13:42 UTC, sysopenci commented
Building VM-Manager Code. For more details refer below link: 
job/satg-aee-android-ci/job/VM-Manager/job/VM-MANAGER-PR-FLOW/202/

2024-04-10 13:49 UTC, sysopenci commented
Build successful. 
job/satg-aee-android-ci/job/VM-Manager/job/VM-MANAGER-PR-FLOW/200/

2024-04-10 13:52 UTC, sysopenci commented
Build successful. 
job/satg-aee-android-ci/job/VM-Manager/job/VM-MANAGER-PR-FLOW/202/

2024-04-10 13:52 UTC, sysopenci commented
Build successful. 
job/satg-aee-android-ci/job/VM-Manager/job/VM-MANAGER-PR-FLOW/201/

2024-04-10 13:59 UTC, bpanda24 approved these changes

2024-04-15 08:07 UTC, YadongQi commented on src/guest/vm_builder_qemu.cc
> +            int result = system("sudo hciconfig hci0 down");
use `boost::process::system()` explicitly.

2024-04-15 08:07 UTC, YadongQi commented on src/guest/vm_builder_qemu.cc
> +constexpr const char *kIntelBtPciAddress = "0000:00:14.0";
I think `00:14.0` is not always IntelBT device, right? There should be another way to detect bluetooth device such like check vendor id or device id.

2024-04-29 07:00 UTC, sysopenci commented
Building VM-Manager Code. For more details refer below link: 
job/satg-aee-android-ci/job/Prod/job/VM-MANAGER-PR-FLOW/208/

2024-04-29 07:11 UTC, sysopenci commented
Build successful. 
job/satg-aee-android-ci/job/Prod/job/VM-MANAGER-PR-FLOW/208/

2024-04-29 07:11 UTC, sysopenci commented
Please find the Deb Package Path : 
artifactory/dev-automation-ba-local/vm-manager-binaries/353/PR/38d4cf8

2024-04-30 09:53 UTC, YadongQi requested changes
Checked the code of passthrough devices, I suggest you modify as below pseudo-code:
```
static void check_bt_device(boost::filesystem::path &p) {
    std::string str_dev(p.string() + "/device");
    int device = ReadSysFile(str_dev.c_str(), std::ios_base::hex);
    std::string str_ven(p.string()  + "/vendor");
    int vendor = ReadSysFile(str_ven.c_str(), std::ios_base::hex);
    //compare the device and vendor with the value from the constant value table you provided, if there is match, then shutdown the hci.
   ...
}

static bool PassthroughOnePciDev(const char *pci_id, PciPassthroughAction action) {
...
    boost::filesystem::path p(kPciDevicePath);
    p.append(pci_id);
    check_bt_device(p);
    p.append("/iommu_group/devices");

    for (boost::filesystem::directory_entry& x : boost::filesystem::directory_iterator(p)) {
...
}
```

And then, the functions you added in utils can all be removed. And BTW, once you submitted new commit, there will be some CI checks, please fix all the issues before you request a review.

2024-04-30 09:53 UTC, YadongQi commented on src/utils/utils.cc
> +const std::string INTEL_VID = "8087:";
please fix the cpp lint issues below. use char instead of string when define global string constant.

2024-05-07 16:35 UTC, closed without merging