PCI device passthrough option for vm-manager
projectceladon/vm_manager pull request #61
Opened 2021-01-02 15:28 UTC by QiaosongZhou

First commit for pci-passthrough feature extension for vm-manager.
Added graphical feature to allow multiple selections in a suboption menu box.
Added secure vfio setup for passthrough devices.

Tracked-On: OAM-95606
Signed-off-by: Qiaosong Zhou <qiaosong.zhou@intel.com>

2021-01-15 00:53 UTC, YadongQi requested changes

2021-01-15 00:53 UTC, YadongQi commented on src/guest/guest.c
> +	// val = g_key_file_get_string(in, g->name, g->key[PCI_PT_USB], NULL);
remove deprecated code

2021-01-16 02:15 UTC, YadongQi commented on src/guest/guest.c
> +	{ "passthrough", { "passthrough_pci", "usb", "udc", "audio", "eth", "wifi", NULL}},
were the "usb", "udc" ... still usefull?

2021-01-16 02:15 UTC, YadongQi commented on src/guest/tui.c
> +// static pop_up_select_menu(WINDOW *parent, const char **opts, int nb_opts, const int selected[]) {
remove?

2021-01-16 02:15 UTC, YadongQi commented on src/guest/tui.c
> +
empty?

2021-01-16 02:15 UTC, YadongQi commented on src/guest/tui.c
> +
why add this new line? remove it

2021-01-16 02:15 UTC, YadongQi commented on src/include/guest/guest.h
> +#define PCI_PT_OPTS_WIFI_STR "wifi"
remove these define if useless

2021-01-16 02:15 UTC, YadongQi commented on src/utils.c
> +void print_regerror (int errcode, size_t length, regex_t *compiled)
take care the coding styles for below codes

2021-01-18 03:26 UTC, QiaosongZhou commented
Completed requested changes, please verify.

2021-01-18 03:57 UTC, YadongQi commented on src/utils.c
> +    char search_key[64] = "ProgIf";
tab as indent

2021-01-18 03:57 UTC, YadongQi commented on src/utils.c
> +	// char pci_device[16] = {0};
remove if useless

2021-01-18 03:57 UTC, YadongQi commented on src/utils.c
> +    int count_res = 0;
ditto

2021-01-18 03:57 UTC, YadongQi commented on src/utils.c
> +    char *options[] = {"lspci", "-vmms", pci_device, (char *)0};
ditto

2021-01-18 03:57 UTC, YadongQi commented on src/utils.c
> +    char *env[] = {(char *)0};
ditto

2021-01-18 03:57 UTC, YadongQi commented on src/utils.c
> +    /* returns number of pci devices found, -1 if error. */
tab as indent

2021-01-18 03:57 UTC, YadongQi commented on src/utils.c
> +    char search_key[64];
ditto

2021-01-18 03:57 UTC, YadongQi commented on src/utils.c
> +    int count_res = 0;
ditto, please check again with below lines

2021-01-18 03:59 UTC, YadongQi commented on src/utils.c
>  #include <errno.h>
add "Tracked-On: OAM-95606" in commit message

2021-01-18 04:05 UTC, YadongQi commented on src/include/utils.h
> +#include <regex.h>
remove these header include, move them to c file.

2021-01-18 06:25 UTC, YadongQi commented on src/guest/start.c
> +			if (f == NULL && !fgets(device, sizeof(device), f)) {
f == NULL || !fgets(device, sizeof(device), f)

2021-01-18 06:35 UTC, YadongQi commented on src/guest/start.c
> +
move these codes between line-554 and line-555.

2021-01-19 07:45 UTC, YadongQi approved these changes

2021-01-19 07:47 UTC, YadongQi approved these changes

2021-01-19 07:47 UTC, YadongQi approved these changes

2021-01-20 06:44 UTC, YadongQi approved these changes

2021-01-20 06:54 UTC, YadongQi approved these changes

2021-01-20 07:01 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2925

2021-01-20 09:23 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2926

Done by "Zhou, Qiaosong" <qiaosong.zhou@intel.com>

2021-01-20 10:19 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1453

Done by "Zhou, Qiaosong" <qiaosong.zhou@intel.com>

2021-01-20 12:35 UTC, merged

2021-01-20 12:36 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Zhou, Qiaosong" <qiaosong.zhou@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/2201