Enable USB Passthrough for TGL
projectceladon/vm_manager pull request #70
Opened 2021-01-25 07:57 UTC by padmashree9110

Updated script for USB passthrough

Tracked-On: OAM-95684
Signed-off-by: Mandri, Padmashree <padmashree.mandri@intel.com>

2021-01-25 15:47 UTC, JeevakaPrabu approved these changes

2021-01-26 00:54 UTC, YadongQi requested changes

2021-01-26 00:54 UTC, YadongQi commented on scripts/start_civ.sh
> +XHCI_CONTROLLERS_VENDORID="a0ed 02ed 06ed 9d2f 9d30 a0ee"
This is not vendor id, right? this is likely the device id.

2021-01-26 00:54 UTC, YadongQi commented on scripts/start_civ.sh
> +        USB_PCI="$USB_PCI $(lspci -nn -D |grep  "USB controller" | grep $i | awk '{print $1}')"
As discussion with Sundar. To add a new option might OK, like --passthrough-usb-tgl-cml or --passthrough-usb-00-14-0 or some other name. Do not modify set_pt_usb(), add a new function instead.

2021-01-26 07:15 UTC, YadongQi approved these changes

2021-01-26 07:24 UTC, YadongQi approved these changes

2021-01-26 12:30 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-celr - r1 (caas), build-celr - r2 (r2_caas) - extra

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2946

2021-01-27 06:41 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2951

Done by "Balan, Swaroop" <swaroop.balan@intel.com>

2021-01-27 07:10 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: Trigger blocking tests Triggered: CIT-CIV-CML-R(cml_nuc:caas - userdebug)

More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1467

2021-01-27 07:44 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: Trigger blocking tests Triggered: CIT-CIV-CML-R(cml_nuc:caas - userdebug)

More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1468

2021-01-27 11:53 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: Trigger blocking tests Triggered: CIT-CIV-CML-R(cml_nuc:caas - userdebug)

More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1471

2021-01-27 12:23 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: Trigger blocking tests Triggered: CIT-CIV-CML-R(cml_nuc:caas - userdebug)

More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1472

2021-01-27 12:56 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: Trigger blocking tests Triggered: CIT-CIV-CML-R(cml_nuc:caas - userdebug)

More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1473

2021-01-27 12:56 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: Trigger blocking tests Triggered: CIT-CIV-CML-R(cml_nuc:caas - userdebug)

More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1474

2021-01-27 17:00 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2954

Done by "Mandri, Padmashree" <padmashree.mandri@intel.com>

2021-01-27 17:46 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1475

Done by "Mandri, Padmashree" <padmashree.mandri@intel.com>

2021-01-27 20:41 UTC, merged

2021-01-27 20:42 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Mandri, Padmashree" <padmashree.mandri@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/2212