Script changes to add missing checks for BT firmware update
projectceladon/vm_manager pull request #92
Opened 2021-05-20 04:35 UTC by aiswaryacyriac

Tracked-On: OAM-97117
Signed-off-by: Aiswarya Cyriac <aiswarya.cyriac@intel.com>

2021-05-20 06:40 UTC, JeevakaPrabu requested changes

2021-05-20 06:40 UTC, JeevakaPrabu commented on scripts/setup_host.sh
> +        read -p "Cold reboot is required, do you want to reboot it NOW? [y/N]" res
reboot or shutdown?

2021-05-21 00:36 UTC, YadongQi approved these changes

2021-05-21 10:40 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/3235

2021-05-24 06:18 UTC, JeevakaPrabu approved these changes

2021-05-24 06:21 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/3236

2021-05-24 06:27 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/3237

2021-05-25 08:48 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds cancelled

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/3239

2021-05-26 11:20 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: Trigger blocking tests Triggered: CIT-CIV-CML-R(cml_nuc:caas - userdebug), CIT-CIV-CML-R(cml_nuc:r2_caas - userdebug), CIT-CIV-TGL-R(tgl_nuc:caas - userdebug), CIT-CIV-TGL-R(tgl_nuc:r2_caas - userdebug)

More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1691

2021-05-27 09:37 UTC, BharatBPanda approved these changes

2021-05-31 04:44 UTC, YadongQi approved these changes

2021-05-31 04:49 UTC, balajim001 approved these changes
LGTM

2021-05-31 10:22 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/3278

Done by "Cyriac, Aiswarya" <aiswarya.cyriac@intel.com>

2021-05-31 12:26 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: Trigger blocking tests cancelled

More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1710

2021-05-31 15:31 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1716

Done by "T Prabhu, Vignesh" <vignesh.t.prabhu@intel.com>

2021-06-01 00:16 UTC, merged

2021-06-01 00:17 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by cactusi@intel.com 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/2389